version: "3.9"

services:
  postgres:
    image: postgres:15.4
    volumes:
      - .volumes/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  application:
    build: .
    container_name: cash
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/restaurant
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    restart: always