spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: 1m
    store-type: redis