spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    timeout: 100m
    store-type: redis
  kafka:
    bootstrap-servers: localhost:9092 #localhost:9092 kafka:9092
  redis:
    host: localhost #redis localhost
    port: 6379