spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  session:
    timeout: 60m
    store-type: redis
  kafka:
    bootstrap-servers: kafka:9092 #localhost:9092 kafka:9092
  redis:
    host: redis #redis localhost
    port: 6379
